// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    $('input').preChange();
    return $('input').on('preChange', function(e, val) {
      var eventTmpl;
      eventTmpl = $("<div class='event ui-new'>" + (Date().match(/\d\d:\d\d:\d\d/).toString()) + ": " + val + "<div/>");
      $('#events').append(eventTmpl);
      $('#events').scrollTop($('#events .event:last').offset().top);
      return eventTmpl.removeClass('ui-new');
    });
  });

}).call(this);
